### ISSUE TITLE
/lay and /spin command error in 1.19.2. Sit works.

### ISSUE THREAD

**Issue by netcore10** [fill1890/FabSit#11]
https://mclo.gs/7eAlvcS

**Comment by fill1890** [comment]
I haven't tested or updated the mod to 1.19.1 yet

I'll look into it soon

**Comment by fill1890** [comment]
Should be resolved in d7e7feb23c441445f7270b9716018df302da9d69 and release 1.5.0

Let me know if you encounter any other issues

**Comment by netcore10** [comment]
I'm still getting the same errors with /lay and /spin https://mclo.gs/X8LodY9 is there an api i might be missing? (Not using curseforge mod manager)

**Comment by fill1890** [comment]
The only dependency is the Fabric API, which the Quilt standard libraries should implement anyway

It *might* be a Quilt related issue but I'm not sure, I'll look into it further and see if I can figure it out

**Comment by fill1890** [comment]
Are you playing in a single player world? I haven't tested single player in a while so that could be the issue - oversight on my part

**Comment by netcore10** [comment]
> Are you playing in a single player world? I haven't tested single player in a while so that could be the issue - oversight on my part

Yes i am.

**Comment by fill1890** [comment]
Latest release (1.5.1) should hopefully fix the issue, let me know how it goes

**Comment by netcore10** [comment]
all good!
